server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: player-service-route
          uri: http://localhost:8081
          predicates:
            - Path=/players/**

        - id: team-service-route
          uri: http://localhost:8082
          predicates:
            - Path=/teams/**

        - id: statistics-service-route
          uri: http://localhost:8083
          predicates:
            - Path=/statistics/**

        - id: game-service-route
          uri: http://localhost:8084
          predicates:
            - Path=/games/**

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.skyhawk: DEBUG

  file:
    name: app.log
    path: /var/log