spring:
  application:
    name: team-service
  datasource:
    url: jdbc:postgresql://127.0.0.1:5434/nba
    username: nbauser
    password: nbapassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled : false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.skyhawk: DEBUG

  file:
    name: app.log
    path: /var/log